### ISSUE TITLE
Does this work with Melonloader 0.5.3?

### ISSUE THREAD

**Issue by GODLIKE-ro** [Astrum-Project/AstralBypass#2]
https://github.com/LavaGang/MelonLoader/releases/tag/v0.5.3 #

**Comment by xKiraiChan** [comment]
0.5.3 crashes for me so I can't create a new signature for it.

Creating a new signature shouldn't be too hard for anyone that has used a debugger like [x64dbg](https://github.com/x64dbg/x64dbg)

**Comment by killerbigpoint** [comment]
@xKiraiChan guide me through it, i'll create signatures for 0.5.3 and 0.5.4

**Comment by xKiraiChan** [comment]
Attach to the game a debugger such as [x64dbg](https://github.com/x64dbg/x64dbg)
Double click `bootstrap.dll` (in the symbols tab)
Right-click then search the current module for string references ("invalid assembly")
There will be 2 results, only 1 of them matters
Find the code that raises the exception, it'll look something like [this](https://github.com/Astrum-Project/AstralBypass/blob/master/IntegrityChecks.cs#L63-L68)
Select the bytes in that area such that there is no collision, then calculate the offset to the target byte
Then you can create a signature and test if it works.

**Comment by EntityReborn** [comment]
I've gone ahead and given this a shot. I'm able to load Munchen correctly, just getting a few people to test. If this works, I'll submit a PR shortly.

**Comment by xKiraiChan** [comment]
It working with Munchen is a bit odd (unless @killerbigpoint made it compatible or only the loader is obfuscated), make sure you check that it still makes integrity checking (knah's) mods work as well

**Comment by EntityReborn** [comment]
I'm currently running Munchen, with UIX, VRTK, etc, no problems.

**Comment by xKiraiChan** [comment]
20778a4
